---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jekyl.
--- DateTime: 4/26/2021 8:18 PM
---
minetest.register_node("alchemy:sol", {
    drawtype = "plantlike",
    description = "Sol Grass",
    light_source = 5, -- The node radiates light. Min 0, max 14
    tiles = {"alchemy_sol_flower.png"},
    groups = {choppy=1, flower=1, flora=1, attached_node=1, snappy=1},
    waving = 1,
    paramtype = "light",
    walkable = false,
    on_use = function(itemstack, player, pointed_thing)
        local pos = player:get_pos()
        minetest.set_node(pos,{name ="fire:basic_flame"})
        itemstack:take_item()
        return itemstack
    end,
    selection_box = {
        type = "fixed",
        fixed = {-2 / 16, -0.5, -2 / 16, 3 / 16, 5 / 16, 2 / 16},
    },
})
minetest.register_node("alchemy:lunar", {
    drawtype = "plantlike",
    description = "Lunar Grass",
    light_source = 1, -- The node radiates light. Min 0, max 14
    tiles = {"alchemy_lunar_flower.png"},
    groups = {choppy=1, flower=1, flora=1, attached_node=1, snappy=1},
    waving = 1,
    paramtype = "light",
    walkable = false,
    on_use = function(itemstack, player, pointed_thing)
        local pos = player:get_pos()
        minetest.set_node(pos,{name ="default:ice"})
        itemstack:take_item()
        return itemstack
    end,
    selection_box = {
        type = "fixed",
        fixed = {-2 / 16, -0.5, -2 / 16, 3 / 16, 5 / 16, 2 / 16},
    },
})

minetest.register_abm({
    nodenames = {"default:dry_dirt_with_grass","default:dry_dirt"},
    neighbor = {"air"},
    interval = 10, -- Run every 10 seconds
    chance = 5000, -- Select every 1 in 50 nodes
    action = function(pos, node, active_object_count, active_object_count_wider)
        local above = {x = pos.x , y = pos.y +1, z = pos.z }

        if not minetest.find_node_near(pos, 2, {"alchemy:sol"}) then
            minetest.set_node(above, {name = "alchemy:sol"})
        end
    end
})
minetest.register_abm({
    nodenames = {"alchemy:sol", "alchemy:lunar", "alchemy:solgrass","alchemy:lunargrass"},
    neighbor = {"air"},
    interval = 5,
    chance = 2,
    action = function(pos, node, active_object_count, active_object_count_wider)
        if node.name == "alchemy:sol" then
            local sols = minetest.find_nodes_in_area_under_air(
                    {x = pos.x - 2, y = pos.y - 1, z = pos.z - 2},
                    {x = pos.x + 2, y = pos.y + 1, z = pos.z + 2},
                    {"alchemy:sol"})
            if (minetest.get_node_light(pos) or 0) <= 12 then
                minetest.set_node({x = pos.x, y = pos.y -1, z = pos.z}, {name = "alchemy:lunargrass"})
                minetest.set_node(pos, {name = "alchemy:lunar"})
                return
            end
            if #sols >= 2 then
                minetest.set_node({x = pos.x, y = pos.y -1, z = pos.z}, {name = "alchemy:solgrass"})
                minetest.set_node(pos, {name = "fire:basic_flame"})

            end
        end
        if node.name == "alchemy:lunar" then
            local luns = minetest.find_nodes_in_area_under_air(
                    {x = pos.x - 2, y = pos.y - 1, z = pos.z - 2},
                    {x = pos.x + 2, y = pos.y + 1, z = pos.z + 2},
                    {"alchemy:lunar"})
            if (minetest.get_node_light(pos) or 0) >= 13 then
                minetest.set_node({x = pos.x, y = pos.y -1, z = pos.z}, {name = "alchemy:solgrass"})
                minetest.set_node(pos, {name = "alchemy:sol"})
                return
            end
            if #luns >= 2 then
                minetest.set_node({x = pos.x, y = pos.y -1, z = pos.z}, {name = "alchemy:lunargrass"})
                minetest.set_node(pos, {name = "default:ice"})

            end
        end
        if node.name == "alchemy:solgrass" then
            if (minetest.get_node_light({x = pos.x, y = pos.y + 1, z = pos.z}) or 0) < 13 then
                minetest.set_node(pos, {name = "alchemy:lunargrass"})
                print("light " .. minetest.get_node_light({x = pos.x, y = pos.y + 1, z = pos.z}))
                return
            end
        end
        if node.name == "alchemy:lunargrass" then
            if (minetest.get_node_light({x = pos.x, y = pos.y + 1, z = pos.z}) or 0) >= 13 then

                minetest.set_node(pos, {name = "alchemy:solgrass"})
                return
            end
        end

    end

})
