---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chandler lyon
--- DateTime: 4/19/2021 10:06 AM
---
local slowheal = slowheal or {}
local time = 0
minetest.register_globalstep(function(dtime)
        time = time + dtime
        if time >= 3 then
            if slowheal[1]~=nil then
                player = minetest.get_player_by_name(slowheal[1])
                if slowheal[2]==1 then
                    player:set_hp(player:get_hp()+1)
                end
            end
            time = 0
        end
end)
minetest.register_craftitem(
        "alchemy:breath_potion",
        {
            description = "Waterbreathing Potion I",
            inventory_image = "alchemy_base_potion.png^[colorize:#0429A5:100",
            on_use = function(itemstack, player, pointed_thing)
                breathIsActive = 1
                firstrun = 0
                minetest.item_eat(0, "alchemy:breath_potion")
                player:set_properties(
                        {
                            breath_max = 1000
                        }
                )
                minetest.after(
                        60,
                        function()
                            player:set_properties({breath_max = minetest.PLAYER_MAX_BREATH_DEFAULT})
                            player:set_breath(10)
                        end
                )
                minetest.after(
                        50,
                        function()
                            minetest.chat_send_player(player:get_player_name(), "you have 10 seconds left of waterbreathing I ")
                        end
                )
            end
        }
)
minetest.register_craftitem(
        "alchemy:fortitude_potion",
        {
            description = "Fortitude Potion I",
            inventory_image = "alchemy_base_potion.png^[colorize:#940000:100",
            on_use = function(itemstack, player, pointed_thing)
                minetest.item_eat(0, "alchemy:fortitude_potion")
                player:set_properties(
                        {
                            hp_max = minetest.PLAYER_MAX_HP_DEFAULT * 2
                        }
                )
                player:set_hp(minetest.PLAYER_MAX_HP_DEFAULT * 2)
                minetest.after(
                        60,
                        function()
                            player:set_properties({hp_max = minetest.PLAYER_MAX_HP_DEFAULT})
                            player:set_hp(10)
                        end
                )
                minetest.after(
                        50,
                        function()
                            minetest.chat_send_player(player:get_player_name(), "you have 10 seconds left of fortitude I")
                        end
                )
            end
        }
)
minetest.register_craftitem(
        "alchemy:invisibility_potion",
        {
            description = "invisibility potion I",
            inventory_image = "alchemy_base_potion.png^[colorize:#708F9F:100",
            on_use = function(itemstack, player, pointed_thing)
                minetest.item_eat(0, "alchemy:invisibility_potion")
                prop =
                player:set_properties(
                        {
                            visual_size = {x = 0, y = 0},
                            is_visible = false
                        }
                )
                player:set_nametag_attributes(
                        {
                            color = {a = 0, r = 255, g = 255, b = 255}
                        }
                )
                minetest.after(
                        60,
                        function()
                            player:set_properties(
                                    {
                                        visual_size = {x = 1, y = 1},
                                        is_visible = true
                                    }
                            )
                            player:set_nametag_attributes(
                                    {
                                        color = {a = 255, r = 255, g = 255, b = 255}
                                    }
                            )
                        end
                )
                minetest.after(
                        50,
                        function()
                            minetest.chat_send_player(player:get_player_name(), "you have 10 seconds left of invisibility I")
                        end
                )
            end
        }
)
minetest.register_craftitem(
        "alchemy:slow_healing_potion",
        {
            description = "slow healing potion I",
            inventory_image = "alchemy_base_potion.png^[colorize:#C91060:100",
            on_use= function(itemstack, player, pointed_thing)
                minetest.item_eat(0, "alchemy:slow_healing_potion")
                slowheal = {player:get_player_name(),1}
                print(slowheal)
                minetest.after(
                        60,
                        function()
                            slowheal = {player:get_player_name(),0}
                        end
                )
                minetest.after(
                        50,
                        function()
                            minetest.chat_send_player(player:get_player_name(), "you have 10 seconds left of slowhealing I ")
                        end
                )
            end
        }
)
minetest.register_craftitem(
        "alchemy:leaping_potion",
        {
            description = "Leaping Potion I",
            inventory_image = "alchemy_base_potion.png^[colorize:#7FFF00:100",
            on_use = function(itemstack, player, pointed_thing)
                breathIsActive = 1
                firstrun = 0
                minetest.item_eat(0, "alchemy:leaping_potion")
                player:set_physics_override({jump=2})
                minetest.after(
                        60,
                        function()
                            player:set_physics_override({jump=1})
                        end
                )
                minetest.after(
                        50,
                        function()
                            minetest.chat_send_player(player:get_player_name(), "you have 10 seconds left of leaping I")
                        end
                )
            end
        }
)
minetest.register_craftitem(
        "alchemy:lunar_potion",
        {
            description = "Lunar Potion I",
            inventory_image = "alchemy_base_potion.png^[colorize:#76b5c5:100",
            on_use = function(itemstack, player, pointed_thing)
                breathIsActive = 1
                firstrun = 0
                minetest.item_eat(0, "alchemy:lunar_potion")
                player:set_physics_override({gravity=0.5})
                minetest.after(
                        60,
                        function()
                            player:set_physics_override({gravity=1})
                        end
                )
                minetest.after(
                        50,
                        function()
                            minetest.chat_send_player(player:get_player_name(), "you have 10 seconds left of lunar I")
                        end
                )
            end
        }
)
minetest.register_craftitem(
        "alchemy:speed_potion",
        {
            description = "Speed Potion I",
            inventory_image = "alchemy_base_potion.png^[colorize:#eae583:100",
            on_use = function(itemstack, player, pointed_thing)
                breathIsActive = 1
                firstrun = 0
                minetest.item_eat(0, "alchemy:lunar_potion")
                player:set_physics_override({speed=2})
                minetest.after(
                        60,
                        function()
                            player:set_physics_override({speed=1})
                        end
                )
                minetest.after(
                        50,
                        function()
                            minetest.chat_send_player(player:get_player_name(), "you have 10 seconds left of speed I")
                        end
                )
            end
        }
)
--todo:
--waterbreathing done
--speed done
--leaping done
--invisibility done
--fortitude_potion done
--nightvision
--fireresistance
--damage
--healing done
