---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jekyl.
--- DateTime: 4/28/2021 9:51 AM
---
powders = {
    {"alchemy_base_powder.png", "alchemy:base_powder"},
    {"alchemy_base_powder.png^[colorize:#c5ec00:50", "alchemy:zap_powder"},
    {"alchemy_base_powder.png^[colorize:#f4d57e:50", "alchemy:sol_powder"},
    {"alchemy_base_powder.png^[colorize:#b32304:50","alchemy:life_powder"},
    {"alchemy_base_powder.png^[colorize:#9dbec3:50", "alchemy:lunar_powder"},
    {"alchemy_base_powder.png^[colorize:#cbf4dc:50", "alchemy:hemlock_powder"},
    {"alchemy_base_powder.png^[colorize:#62f9e3:50", "alchemy:fractalized_powder"},
    {"alchemy_base_powder.png^[colorize:#3852d6:50", "alchemy:oceanic_powder"},
}
function reg_powders( tex, pow)
    str1 = string.gsub(pow, "alchemy:", "")
    str2 = string.gsub(str1, "_", " ")
    minetest.register_craftitem(
            pow,
            {
                description = str2 ,
                inventory_image = tex,
            }
    )
end
for i in ipairs(powders) do
    reg_powders(powders[i][1],powders[i][2])
end