---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jekyl.
--- DateTime: 4/21/2021 10:55 PM
---
local eth = minetest.get_modpath("ethereal")-- probably not a permanent depend.
local buck = minetest.get_modpath("bucket")
if buck then

    minetest.register_craft({
        output = "alchemy:tube",
        recipe = {
            {"", "default:glass", ""},
            {"", "default:glass", ""},
            {"", "default:glass",""}
        }
    })
    minetest.register_craft({
        output = "vessels:glass_bottle",
        recipe = {
            {"", "", ""},
            {"", "alchemy:tube", ""},
            {"", "",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:potion",
        recipe = {
            {"", "", ""},
            {"alchemy:hemlock", "vessels:glass_bottle", "alchemy:hemlock"},
            {"", "bucket:bucket_water", ""}
        }
    })
    minetest.register_craft({
    output = "alchemy:base_throw_potion",
    recipe = {
        {"", "alchemy:glass_bottle", ""},
        {"", "alchemy:potion", ""},
        {"", "default:mese_crystal", ""}
    }
})
    minetest.register_craft({
        output = "alchemy:breath_potion",
        recipe = {
            {"", "alchemy:oceanic_powder", ""},
            {"alchemy:oceanic_powder", "alchemy:potion", "alchemy:oceanic_powder"},
            {"alchemy:oceanic_powder", "bucket:bucket_water", "alchemy:oceanic_powder"}
        }
    })
    minetest.register_craft({
        output = "alchemy:fortitude_potion",
        recipe = {
            {"alchemy:life_powder", "alchemy:eye_of_earth", "alchemy:life_powder"},
            {"alchemy:sol", "alchemy:potion", "alchemy:sol"},
            {"default:mese_crystal", "alchemy:life_powder","default:mese_crystal"}
        }
    })
    minetest.register_craft({
        output = "alchemy:invisibility_potion",
        recipe = {
            {"alchemy:fractalized_powder", "alchemy:zap_powder", "alchemy:fractalized_powder"},
            {"alchemy:eye_of_earth", "alchemy:potion", "alchemy:eye_of_sand"},
            {"default:mese_crystal", "alchemy:sol_powder","default:mese_crystal"}
        }
    })
    minetest.register_craft({
        output = "alchemy:slow_healing_potion",
        recipe = {
            {"alchemy:life_powder", "alchemy:life", "alchemy:life_powder"},
            {"alchemy:arboreal_tooth", "alchemy:potion", "alchemy:arboreal_tooth"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:leaping_potion",
        recipe = {
            {"alchemy:zap_powder", "alchemy:lunar_powder", "alchemy:zap_powder"},
            {"", "alchemy:potion", ""},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:lunar_potion",
        recipe = {
            {"default:mese", "", "default:mese"},
            {"alchemy:arboreal_tooth", "alchemy:potion", "alchemy:arboreal_tooth"},
            {"alchemy:lunar_powder", "alchemy:lunar_powder","alchemy:lunar_powder"}
        }
    })
    minetest.register_craft({
        output = "alchemy:speed_potion",
        recipe = {
            {"default:mese", "alchemy:zap_powder", "default:mese"},
            {"alchemy:zap_powder", "alchemy:potion", "alchemy:zap_powder"},
            {"", "alchemy:zap_powder",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:nightvision_potion",
        recipe = {
            {"default:meselamp", "alchemy:zap_powder", "default:meselamp"},
            {"alchemy:sol_powder", "alchemy:potion", "alchemy:lunar_powder"},
            {"alchemy:fractalized_powder", "default:mese_crystal","alchemy:fractalized_powder"}
        }
    })
    minetest.register_craft({
        output = "alchemy:poison",
        recipe = {
            {"default:mese", "alchemy:hemlock_powder", "default:mese"},
            {"default:mese_crystal", "alchemy:potion", "default:mese_crystal"},
            {"alchemy:hemlock_powder", "default:mese_crystal","alchemy:hemlock_powder"}
        }
    })

    ----------------throw potion----------------
    minetest.register_craft({
        output = "alchemy:breath_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:breath_potion", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:fortitude_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:fortitude_potion", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:invisibility_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:invisibility_potion", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:slow_healing_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:slow_healing_potion", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:leaping_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:leaping_potion", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:lunar_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:lunar_potion", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:speed_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:speed_potion", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:nightvision_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:nightvision_potion", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })
    minetest.register_craft({
        output = "alchemy:poison_throwpotion",
        recipe = {
            {"", "default:mese_crystal", ""},
            {"default:mese_crystal", "alchemy:poison", "default:mese_crystal"},
            {"", "default:mese_crystal",""}
        }
    })

    minetest.register_craftitem("alchemy:tube", {
        description = "Empty tube",
        inventory_image = "alchemy_tube.png",
    }) --needed for compatability.

end