---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jekyl.
--- DateTime: 4/21/2021 10:55 PM
---
local eth = minetest.get_modpath("ethereal")-- probably not a permanent depend.
local buck = minetest.get_modpath("bucket")
if eth and buck then
    minetest.register_craft({
        output = "alchemy:base_potion",
        recipe = {
            {"", "", ""},
            {"", "", ""},
            {"", "", ""}
        }
    })
    minetest.register_craft({
    output = "alchemy:base_throw_potion",
    recipe = {
        {"", "alchemy:base_potion", ""},
        {"", "alchemy:base_potion", ""},
        {"", "", ""}
    }
})
    minetest.register_craft({
        output = "alchemy:breath_potion",
        recipe = {
            {"ethereal:coral4", "ethereal:frost_leaves", "ethereal:coral4"},
            {"ethereal:crystal_dirt", "alchemy:base_potion", "alchemy:arboreal_tooth"},
            {"ethereal:coral4", "bucket:bucket_water", "ethereal:coral4"}
        }
    })
    minetest.register_craft({
        output = "alchemy:fortitude_potion",
        recipe = {
            {"ethereal:illumishroom", "alchemy:arboreal_tooth", "ethereal:illumishroom"},
            {"alchemy:eye_of_earth", "alchemy:base_potion", "alchemy:eye_of_sand"},
            {"ethereal:illumishroom2", "alchemy:fire_essence","ethereal:illumishroom3"}
        }
    })
    minetest.register_craft({
        output = "alchemy:invisibility_potion",
        recipe = {
            {"default:meselamp", "ethereal:crystal", "default:meselamp"},
            {"alchemy:arboreal_tooth", "alchemy:base_potion", "alchemy:eye_of_sand"},
            {"default:meselamp", "ethereal:fire_dust","default:meselamp"}
        }
    })
    minetest.register_craft({
        output = "alchemy:slow_healing_potion",
        recipe = {
            {"default:mese", "ethereal:coral5", "default:mese"},
            {"alchemy:arboreal_tooth", "alchemy:base_potion", "alchemy:arboreal_tooth"},
            {"ethereal:banana_bread", "ethereal:coral5","ethereal:agar_powder"}
        }
    })
    minetest.register_craft({
        output = "alchemy:leaping_potion",
        recipe = {
            {"default:mese", "ethereal:coral5", "default:mese"},
            {"alchemy:arboreal_tooth", "alchemy:base_potion", "alchemy:arboreal_tooth"},
            {"ethereal:banana_bread", "ethereal:coral5","ethereal:agar_powder"}
        }
    })
    minetest.register_craft({
        output = "alchemy:lunar_potion",
        recipe = {
            {"default:mese", "ethereal:coral5", "default:mese"},
            {"alchemy:arboreal_tooth", "alchemy:base_potion", "alchemy:arboreal_tooth"},
            {"ethereal:banana_bread", "ethereal:coral5","ethereal:agar_powder"}
        }
    })
    minetest.register_craft({
        output = "alchemy:speed_potion",
        recipe = {
            {"default:mese", "ethereal:coral5", "default:mese"},
            {"alchemy:arboreal_tooth", "alchemy:base_potion", "alchemy:arboreal_tooth"},
            {"ethereal:banana_bread", "ethereal:coral5","ethereal:agar_powder"}
        }
    })
    minetest.register_craft({
        output = "alchemy:nightvision_potion",
        recipe = {
            {"default:mese", "ethereal:coral5", "default:mese"},
            {"alchemy:arboreal_tooth", "alchemy:base_potion", "alchemy:arboreal_tooth"},
            {"ethereal:banana_bread", "ethereal:coral5","ethereal:agar_powder"}
        }
    })
end