---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jekyl.
--- DateTime: 4/23/2021 9:01 AM
---
alchemy = {players = {}}
potions = {
    {"alchemy_base_potion.png^[colorize:#0429A5:100", "alchemy:breath_potion"},
    {"alchemy_base_potion.png^[colorize:#940000:100", "alchemy:fortitude_potion"},
    {"alchemy_base_potion.png^[colorize:#708F9F:100", "alchemy:invisibility_potion" },
    {"alchemy_base_potion.png^[colorize:#C91060:100", "alchemy:slow_healing_potion"},
    {"alchemy_base_potion.png^[colorize:#7FFF00:100", "alchemy:leaping_potion"},
    {"alchemy_base_potion.png^[colorize:#76b5c5:100", "alchemy:lunar_potion"},
    {"alchemy_base_potion.png^[colorize:#eae583:100", "alchemy:speed_potion"},
    {"alchemy_base_potion.png^[colorize:#00720d:100","alchemy:nightvision_potion"}
}
 function throwables( tex, pot)
    local function throw_potion(itemstack, player)
        local playerpos = player:get_pos()
        local obj = minetest.add_entity({
            x = playerpos.x,
            y = playerpos.y + 1.5,
            z = playerpos.z
        }, pot .. "_entity")
        local dir = player:get_look_dir()
        local velocity = 20
        obj:set_velocity({
            x = dir.x * velocity,
            y = dir.y * velocity,
            z = dir.z * velocity
        })
        obj:set_acceleration({
            x = dir.x * -3,
            y = -9.5,
            z = dir.z * -3
        })
        obj:set_yaw(player:get_look_horizontal())
        obj:get_luaentity().player = player
    end
    -- potion entity
    local potion_entity = {
        physical = true,
        visual = "sprite",
        visual_size = {x = 1.0, y = 1.0},
        textures = {tex},
        collisionbox = {-0.1,-0.1,-0.1,0.1,0.1,0.1},
        lastpos = {},
        player = ""
    }
    potion_entity.on_step = function(self, dtime)


        if not self.player then
            self.object:remove()
            return
        end
        local pos = self.object:get_pos()
        if self.lastpos.x ~= nil then
            local vel = self.object:get_velocity()
            -- only when potion hits something physical
            if vel.x == 0
                    or vel.y == 0
                    or vel.z == 0 then
                if self.player ~= "" then
                    local closest_d = 999
                    local closest_name
                    for i, obj in ipairs(minetest.get_objects_inside_radius(pos,3)) do
                        -- 5.0.0+ method:
                        if minetest.is_player(obj) then
                            local distance = vector.length(vector.subtract(obj:get_pos(), pos))
                            if distance < closest_d then
                                closest_d = distance
                                closest_name = obj
                            end
                        end
                    end
                    --end player finding
                    -- round up coords to fix glitching through doors
                    if closest_name~= nil then
                        player = closest_name
                        minetest.chat_send_all(player:get_player_name() .. " has been hit with a splash potion of" .. pot .. "!")
                        --effect of whatever pot is, goes here.

                        end

                    end
                end
                self.object:remove()
                return
            end
        end
     
        self.lastpos = pos

    minetest.register_entity(pot .. "_entity", potion_entity)

    minetest.register_craftitem(
            pot .. "_throw",
            {
                description = "throwable" .. pot ,
                inventory_image = "alchemy_base_potion.png^[colorize:#eae583:100",
                on_use = function(itemstack, player, pointed_thing)
                    throw_potion(itemstack, player)
                    itemstack:take_item()
                    return itemstack
                end
            }
    )
     return tplayer
 end
